import argparse
import json
import warnings
from pathlib import Path

import torch

from train import EdgeRiceNet


def parse_args():
    parser = argparse.ArgumentParser(description="Export a PyTorch Mobile edge model.")
    parser.add_argument(
        "--checkpoint",
        type=Path,
        default=Path("artifacts") / "rice_leaf_edge_model.pt",
        help="Path to a training checkpoint generated by train.py",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("edge_artifacts"),
        help="Directory where edge-ready artifacts will be written",
    )
    parser.add_argument(
        "--prune-amount",
        type=float,
        default=0.0,
        help="Optional unstructured pruning ratio for conv/linear weights before export",
    )
    return parser.parse_args()


def load_model(checkpoint_path: Path):
    checkpoint = torch.load(checkpoint_path, map_location="cpu")
    classes = checkpoint["classes"]
    image_size = checkpoint["image_size"]
    model = EdgeRiceNet(num_classes=len(classes))
    model.load_state_dict(checkpoint["model_state_dict"])
    model.eval()
    return model, classes, image_size


def maybe_prune_model(model: torch.nn.Module, amount: float) -> torch.nn.Module:
    if amount <= 0:
        return model

    import torch.nn.utils.prune as prune

    modules_to_prune = []
    for module in model.modules():
        if isinstance(module, (torch.nn.Conv2d, torch.nn.Linear)):
            modules_to_prune.append((module, "weight"))

    if modules_to_prune:
        prune.global_unstructured(
            modules_to_prune,
            pruning_method=prune.L1Unstructured,
            amount=amount,
        )
        for module, name in modules_to_prune:
            prune.remove(module, name)

    return model


def export_torchscript_variants(model: torch.nn.Module, output_dir: Path):
    scripted_model = torch.jit.script(model)
    scripted_model.save(str(output_dir / "rice_leaf_edge_scripted.pt"))
    scripted_model._save_for_lite_interpreter(str(output_dir / "rice_leaf_edge_mobile.ptl"))
    return scripted_model


def export_quantized_mobile_model(model: torch.nn.Module, output_dir: Path):
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", category=DeprecationWarning)
        quantized_model = torch.quantization.quantize_dynamic(
            model,
            {torch.nn.Linear},
            dtype=torch.qint8,
        )
    scripted_quantized = torch.jit.script(quantized_model)
    scripted_quantized.save(str(output_dir / "rice_leaf_edge_mobile_int8.pt"))
    scripted_quantized._save_for_lite_interpreter(
        str(output_dir / "rice_leaf_edge_mobile_int8.ptl")
    )
    return quantized_model


def artifact_sizes(output_dir: Path):
    return {
        path.name: path.stat().st_size
        for path in sorted(output_dir.iterdir())
        if path.is_file()
    }


def main():
    args = parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)

    model, classes, image_size = load_model(args.checkpoint)
    model = maybe_prune_model(model, args.prune_amount)

    export_torchscript_variants(model, args.output_dir)
    export_quantized_mobile_model(model, args.output_dir)

    summary = {
        "checkpoint": str(args.checkpoint.resolve()),
        "classes": classes,
        "image_size": image_size,
        "prune_amount": args.prune_amount,
        "artifacts": artifact_sizes(args.output_dir),
    }

    summary_path = args.output_dir / "edge_export_summary.json"
    summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
